name: merlin_editor
description: "Create Shmup games with ease with Flutter and Flame"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  merlin:
    path: packages/merlin
  nes_ui: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
